### ISSUE TITLE
What would be the comparable solution to consume messages from Kafka and send to either prometheus or cortex?

### ISSUE THREAD

**Issue by wahabz** [sukhinin/prometheus-kafka-writer#1]
Hi,

Nice work on writing the prometheus metrics to Kafka. However, what is the solution to consume from Kafka and output to a database that can be used to visualize?

**Comment by sukhinin** [comment]
Hi,

Data serialised with `ClickHouseJsonSerializer` can be directly consumed from Kafka topic by ClickHouse DBMS (see [ClickHouse docs](https://clickhouse.tech/docs/en/engines/table-engines/integrations/kafka/) for details). There's a ClickHouse plugin for Grafana if you're interested in visualisations.

Regarding sending data from Kafka back to Prometheus, I don't see how this could work. Prometheus has to seek and filter data, and Kafka provides sequential access only. I wrote another adapter, [prometheus-clickhouse-reader](https://github.com/sukhinin/prometheus-clickhouse-reader), that can be used to query data stored in ClickHouse from Prometheus, but it's untested and undocumented.

**Comment by wahabz** [comment]
Hi,

I like the ClickHouse plugin. However in my scenario, I want to be able to send from Kafka to Cortex. 

Could this work?
Use logstash to consume prometheus metrics in json format (sample message I pulled from Kafka topic using logstash consumer).
{"value":"201802712","timestamp":"2020-09-13T13:37:13Z","@version":"1","labels":{"instance":"worker-3","dc":"eastlake","endpoint":"https","pod":"node-exporter-tg42l","job":"node-exporter","__name__":"node_mountstats_nfs_event_inode_revalidate_total","prometheus_replica":"prometheus-k8s-1","namespace":"openshift-monitoring","prometheus":"openshift-monitoring/k8s","service":"node-exporter","protocol":"tcp","export":"172.20.102.13:/trident_qtree_pool_welk_kub2_EEOGNFQUWE/welk_kub2_pvc_e7b8ee78_8a9a_4457_bb39_d3325c405ddb"},"@timestamp":"2020-09-14T20:52:31.307Z","name":"node_mountstats_nfs_event_inode_revalidate_total"}

Then use some sort of filtering on logstash to convert the message the format as requires in this: https://github.com/m3dbx/prometheus_remote_client_golang to remote write the sample to cortex (https://github.com/cortexproject/cortex)?

**Comment by sukhinin** [comment]
I have no experience with Cortex, but according to docs it acts as a Prometheus remote write backend, so at a first glance such setup is possible. 

Prometheus remote write backend expects metrics in a Snappy-compressed Protobuf message over HTTP, not sure if Logstash can handle that. If it's not, I would probably go with a small custom application consuming data from Kafka, reformatting it as needed and writing to Cortex endpoint.

**Comment by sukhinin** [comment]
Closing this issue as it is not directly related to prometheus-kafka-writer, but rather a general Prometheus / Kafka integration question.
