### ISSUE TITLE
What URL is to be written in prometheus remote_write in prometheus.yml file?

### ISSUE THREAD

**Issue by Roshmik236** [sukhinin/prometheus-kafka-writer#2]
I have correctly imported the jar file and also ran it but it not producing the desired output.

**Comment by sukhinin** [comment]
The URL depends on where you run prometheus-remote-writer. If it's the same server as Prometheus, then prometheus.yml should contain something like
```
remote_write:
  - url: 'http://localhost:8080/'
```

**Comment by Roshmik236** [comment]
I have given remote_write:
  - url: 'http://localhost:8080/metrics' and its working fine.
  
Thanks.
