### ISSUE TITLE
Problems with connecting via prometheus remote write

### ISSUE THREAD

**Issue by GLucaDEV** [sukhinin/prometheus-kafka-writer#3]
Hey, first of all thanks for your project!
But I got a problem with remote writing.
As in the issue before suggestet, I tried setting the remote write in prometheus to http://localhost:8080/metrics and also tried it without metrics. But I always get a connection refused :(
do you have any tips how to solve this problem?

btw, I am running prometheus in a docker container

thanks

**Comment by sukhinin** [comment]
Hi! First of all, do you run prometheus itself and prometheus-kafka-writer on the same server? Can you show me `remote_write` portion of prometheus config and `server.port` config value of prometheus-kafka-writer?

**Comment by GLucaDEV** [comment]
Hey, thanks for your fast reply, I managed to solve it myself. I needed to use "host.docker.internal" instead of localhost

**Comment by sukhinin** [comment]
Glad to hear that! Good luck!
